### PR TITLE
macOS is now supported

### PR DESCRIPTION
**Pull request by Platinum-Phoenix**

### CODE REVIEW

**Comment by Fenex330** [comment]
could not successfully compile and link on macOS

**Comment by Platinum-Phoenix** [comment]
What generator did you use? Using Unix Makefiles works for me.

**Comment by Fenex330** [comment]
@Platinum-Phoenix I recompiled again and it actually works. The only problem is that it does not work with relative paths, so if I move the bin folder somewhere else, dylib files do not link at runtime. It also does not load the main sprite image.

**Comment by Fenex330** [comment]
Please create separate pull requests for each feature/issue resolved

**Comment by Platinum-Phoenix** [comment]
Ok. I'll try.

**Pull request closed without merging**
